sudo: required
git:
  depth: 3
  submodules: true
env:
  matrix:
  - OS_TYPE=ubuntu OS_VERSION=18.04 OS_NAME=bionic
services:
- docker
addons:
  apt:
    update: true
before_install:
- sudo apt-get -qq update
- sudo docker pull ${OS_TYPE}:${OS_VERSION}
script:
- docker run -ti -v ${TRAVIS_BUILD_DIR}:/work:rw ${OS_TYPE}:${OS_VERSION} /bin/bash -c "cd /work; ./tests.sh ${OS_TYPE} ${OS_NAME}"
before_deploy:
- cd ${TRAVIS_BUILD_DIR}
- dpkg-deb -b tmp libhermit-rs-0.3.9-all.deb
deploy:
  provider: bintray
  on:
    branch: master
  skip_cleanup: true
  file: ".bintray_descriptor.json"
  key:
    secure: YgqGaOal6kVGeZ+cc2PLU1IAHFdmT2koFWhi8bB2ZfvPJ0iX7JCikL6A/gnh41wQu+AaUKYQDAZwUE7IRB5j+avMKkvNskDb1GWTbEjOiWuzJGQL4Ftjn2p8M88KJ88L6hGPS5bRPPYMWmKzaF7KKJy9ehlYRUiJTozpq921sEa5RuYsOPS3KLsvru5jVeOJSnbnW1WDYqVxDg1gbjRBjE/wVfVz16MpGtKZ/EL/rf0aP/9jE36TrLc26rNzEvNNofB24cvNT7eZRataAKX2tEdtcwsokuqi55RcfnZbc0ykb8Du3jFChjIfU7Qm+sDxFWjtRkLL7Zw1hJHkUgu624b1cz97hzxMwws6ssrjyyzu2Axum5EcMH1xp/pQm2Zw32BpbwBkB1nnqTXLf7SGNgHNMk6Y6TP0KZKCdTGhxM3dcFHqV9yCCiV/T+nBFB67uwc4VzdZPZGxzEB+iU0M+Bb116gTCT2tjg42bxjovpDuHAoV6DtnB5x0+mYNYU04PRRvHm/0tFrM9BU1SrcnSXk9J3ndaBcEWIz3WHSvAUB2M0CxUaaXfVeJ4stlXd+ENcrK2KMdQYcFF8egWUtNGZpPdH5dERuuUW8YhmIXWYRb+W42kbJN/nsPezrYfYLpqENprmbO1A4GpXD6GGhp4/p2ZaJEHDYGFOYRAPFjKPE=
  user:
    secure: LnC19RPsvuQbHV11GbbWxgGDk3tbUNFk67IC8VtrHxDubFtBo8x84ibreyLiFdfJOaW9WFUXIEFiCj/j9/0n3cUq1rVzZNFPyEYqyPROWuVJLgkdfvLqfI+JxrXejDe2PONyumUHREQt+zFVnDjSkULoU1QDuXYICYU6WAQRLzvxnhFDp6FPUPA0vSdpSR+zyJeHeXh19JFCF3aJ1Vjw5bKW3F2QeT5wctdWHzmxRGK5dKtIpZjeAysGlb0NaPhBD/NWArMmfgKcfbrcBm9U+bLUDFj0tLmzPc3pEfdBdAYcKokVvPfJHngBlGUrbLsEyrA5vMTIk2Clr9nc9cBlABQTKrPPK9YxWOfM/AKjzOQPfE1SNHoUMI6cwKy8nOwjFs/JRVKk+v81gYSKwu157vnkvFVzKJ2350GAPg6Epq1o0cTbvKoJSYxWqXQVzZlPb8i2XqOzKOYxLRDDyMZRWR3AivysXa3rF5JT9heFP7XKPQeeYLoQx5ywghAmcsbUQEVw3VUZaL4AipJ5wxWN1sO6VFVjVQ/w9W9sw7A+qlbX8dTyOehhJnzvihd4qtFX2pIc8EGKBQ0tAznJJ+uBEp8B/SEUaAAXE6HtU1sAVAze2iElDTk3076k4T3cFL8q2uE+vN8SQF5k7BohGkMBLFqyxztTF3mPsGurwf2+lxk=
