name: Test x86_64

on:
  pull_request:
  merge_group:
  push:
    branches:
      - bench

jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Download loader
      uses: dsaltares/fetch-gh-release-asset@master
      with:
        repo: hermit-os/loader
        version: tags/v0.5.0
        file: hermit-loader-x86_64
    - name: Install QEMU
      run: |
        sudo apt-get update
        sudo apt-get -y install qemu-system-x86
    - name: Run benchmarks
      uses: CarlWachter/hermit-bench@hermit-playground
      with: 
        benchmark-file: /usr/benchmarks/bench.json
        build-command: "'HERMIT_LOG_LEVEL_FILTER=Off mkdir build && cd build && cmake .. -DTOOLCHAIN_BIN_DIR=/home/carl/test/new/bin && make'"
    - name: Store benchmark result
      uses: CarlWachter/github-action-benchmark@playground
      with:
        # What benchmark tool the output.txt came from
        tool: 'customSmallerIsBetter'
        # Where the output from the benchmark tool is stored
        output-file-path: results.json
        # Where the previous data file is stored
        #external-data-json-path: ./cache/benchmark-data.json
        # Publish to Pages on
        github-token: ${{ secrets.GITHUB_TOKEN }}
        auto-push: true